### ISSUE TITLE
Support Docker Labels to identify a site for a certificate

### ISSUE THREAD

**Issue by febbraro** [eforce21/letsencrypt-nginx-proxy#4]
We have a setup using this for a pretty large environment (50+ containers) and only a few of them are meant to be "public" and would require an SSL cert.  Given that the current rate limits are **5 certificates per domain every 7 days** it would take us weeks to get all the certs (and we dont even really need them). It would be fantastic if we could use Docker labels on containers to identify them as a container we want to request a certificate for.  Something simple like `letsencrypt.cert=true`.  I would be happy to look into providing a PR around this, but it appears that createSSL.sh is an executable and not a shell script that I could look at modifying.

Happy to help though, but the opportunity appears to be limited.

**Comment by sopitz** [comment]
Thanks for the request! That's a good point. If you want to go ahead and give it a shot you can have a look at the ssl.tmpl file. This will be used to generate the createSSL.sh in the end. We just had to check it in with chmod +x as it wouldn't be executable after generation otherwise. 

Did that help you? I'll have a look into it tomorrow as well.

**Comment by sopitz** [comment]
Even though I think turning it around and excluding containers would be better. So we can maintain an easy flow for users who want all their containers with SSL support and only make those users configure more who need it.

**Comment by febbraro** [comment]
I can certainly see both sides of that argument.  My presumption was that rate limits were so extreme that it made sense to opt-in instead of opt-out. Once the label thing is figured out it will be pretty simple to reverse, or even make that configurable with a ENV var passed to the proxy.

**Comment by febbraro** [comment]
How do you generate that createSSL.sh script?  In order for me to test it before I PR, I'll need to do that or can we integrate the compilation into the Dockerfile itself?

**Comment by sopitz** [comment]
Unfortunately we cannot integrate that in the Dockerfile as we need to do that every time a container is started. You can have a look into the Procfile. That's where the docker-gen command is started. This one watches for container startups, uses the ssl.tmpl and generates the createSSL.sh on the fly.

**Comment by sopitz** [comment]
I created a basic solution in this branch: https://github.com/eforce21/letsencrypt-nginx-proxy/tree/feature/nocert-label

So there's an update to the ssl.tmpl and that should do the trick.
For now you would have to run your containers with `--label letsencrypt.nocert=true`. In the template we only check for the existence of `--label letsencrypt.nocert` but you need to assign it a value so that docker runs the container. All containers who don't have that label and have a `-e VIRTUAL_HOST=<something>`will then be selected for generation within createSSL.sh.

What do you think?

**Comment by sopitz** [comment]
@febbraro could you take a look if that would solve your issue already? Otherwise I would merge that feature today and release it as it might be of relevance to others too.

**Comment by febbraro** [comment]
I plan on looking at it today. The only thing I was considering would be an environment variable passed to the container on startup. Something like `-e LETSENCRYPT_OPT_IN=true` and if that is specified we do 

`$sslContainers := whereLabelExist $ "letsencrypt.cert"` 

otherwise we do 

`$sslContainers := whereLabelDoesNotExist $ "letsencrypt.nocert"` 

like you have now. That lets the user decide if they want opt-in or opt-out semantics.  If it makes it easier, we can merge what you have now in place and I can work on a PR to add what I have described above.

Thanks so much for your attention on this (and for releasing this container in general)

**Comment by febbraro** [comment]
Added a PR back to your branch with my ideas on opt in/opt out. Let me know what you think.

https://github.com/eforce21/letsencrypt-nginx-proxy/pull/6

**Comment by febbraro** [comment]
@sopitz Any feedback or different direction you think this should take?

**Comment by sopitz** [comment]
I merged #6 and released it! Thanks @febbraro for your help and feature request!
